### PR TITLE
Adding additional object to response

### PR DESCRIPTION
**Pull request by TheSuperFly**
Hello, 

I did this improvement since passing an object through the initial parameter shows it as `[object Object]`. And I need to pass through message an object since I'm using Boom with express-validator.

WDYT of this?

### CODE REVIEW

**Comment by scottcorgan** [comment]
Seems like a good idea. Can you show me a code sample?

**Comment by TheSuperFly** [comment]
Of couse ! Here is one I'm using many times with `express-validator`, passing through his own error object.

```
req.check(schema);

req.getValidationResult().then((result) => {
    if (!result.isEmpty()) {
      return res.boom.badRequest('validation has failed', result.mapped());
    }

    // code ...
});
```

**Comment by scottcorgan** [comment]
Thanks! Published as `2.0.0`

**Comment by TheSuperFly** [comment]
My thanks to you !

**Pull request merged**
