### PR TITLE
Updating the boom version.

### PR DESCRIPTION
**Pull request by felipewmartins**

### CODE REVIEW

**Comment by scottcorgan** [comment]
@felipewmartins do you know what the breaking changes were from 3.x to 7.x? I want to make sure things don't break 👍

**Comment by felipewmartins** [comment]
@scottcorgan  I will go make more tests.

**Comment by felipewmartins** [comment]
Hi @scottcorgan 
I put a suite of tests in the project.

**Comment by scottcorgan** [comment]
This is awesome. I'll merge and get a new version published! Thank you!

**Comment by scottcorgan** [comment]
Published as `3.0.0`

**Pull request merged**
